import APICustomizerHeader from "@/components/APICustomizerHeader";
import NodeGroup from "@/components/NodeGroup";
import TargetPageDOMInstance from "@/components/TargetPageDOMInstance";
import UpdateLayout from "@/components/UpdateLayout";
import ScrapperProvider, { ScrapperContext } from "@/context/ScrapperContext";
import ScrapperUpdateProvider from "@/context/ScrapperContextUpdate";
import { Layout } from "antd";
import Head from "next/head";

export default function CrawlerTemplate({ data }) {
	const pageData = data.crawler;
	const pageTitle = `${pageData.apiName} API | Pirate Crawler`;
	return (
		<>
			<ScrapperUpdateProvider>
				<Head>
					<title>{pageTitle}</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<UpdateLayout pageData={pageData} />
			</ScrapperUpdateProvider>
		</>
	);
}

export async function getServerSideProps(context) {
	const { id } = context.params;
	let resp = await fetch(`${process.env.NEXT_PUBLIC_SITE_URL}api/crawlers?id=${id}`);
	resp = await resp.json();
	return {
		props: { data: resp },
	};
}
