import { useContext, useEffect } from "react";
import Head from "next/head";
import AppHeader from "@/components/AppHeader";
import { Layout, Menu, theme, Card, Button } from "antd";
import TargetPageDOMInstance from "@/components/TargetPageDOMInstance";
import ScrapperProvider, { ScrapperContext } from "@/context/ScrapperContext";
import NodeGroup from "@/components/NodeGroup";
import APICustomizerHeader from "@/components/APICustomizerHeader";
const { Content, Sider } = Layout;

export default function CrawlerCreate() {
	const { scrapeTargets } = useContext(ScrapperContext);

	return (
		<>
			<Head>
				<title>Create New Crawler | Pirate Crawler</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout>
				<ScrapperProvider>
					<APICustomizerHeader type="Create" />
					<Content>
						<Layout>
							<Sider width={300} className="setting-controls">
								<NodeGroup />
							</Sider>
							<Content className="pa-4 target-page__preview">
								<TargetPageDOMInstance />
							</Content>
						</Layout>
					</Content>
				</ScrapperProvider>
			</Layout>
		</>
	);
}
