import Head from "next/head";
import { Button, Typography } from "antd";
import React from "react";
import DashboardLayout from "@/components/DashboardLayout";
const { Title } = Typography;
import { Table } from "antd";
import type { ColumnsType } from "antd/es/table";
import { getSession } from "next-auth/react";
import TableAction from "@/components/TableAction";
import Link from "next/link";

interface DataType {
	key: string;
	name: string;
	url: string;
}

export default function Crawlers({ pageData }) {
	const columns: ColumnsType<DataType> = [
		{
			title: "Name",
			dataIndex: "name",
			key: "name",
			render: (text, record) => <Link href={`/dashboard/crawlers/${record.key}`}>{text}</Link>,
		},
		{
			title: "Url",
			dataIndex: "url",
			key: "url",
		},
		{
			title: "Action",
			key: "action",
			render: (text, record) => <TableAction crawlData={record} />,
		},
	];

	const data: DataType[] = pageData.crawler.map((d, i) => {
		return {
			key: d._id,
			name: d.apiName,
			url: d.targetUrl,
		};
	});

	return (
		<>
			<Head>
				<title>Crawler API's | CopyKat</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<DashboardLayout>
				<div className="container">
					<div className="data-table__header">
						<Title level={2}>Crawlers</Title>
						<Link href={"/dashboard/crawlers/create"}>
							<Button type="primary">Create New+</Button>
						</Link>
					</div>
					<Table columns={columns} dataSource={data} />
				</div>
			</DashboardLayout>
		</>
	);
}

export async function getServerSideProps({ req }) {
	const session = await getSession({ req });
	//@ts-ignore
	let crawlers = await fetch(
		`${process.env.NEXT_PUBLIC_SITE_URL}api/crawlers/getByUserEmail?email=${session.user.email}`
	);
	crawlers = await crawlers.json();
	return { props: { pageData: crawlers } };
}
