import Head from "next/head";
import { Card, Typography } from "antd";
import React from "react";
import DashboardLayout from "@/components/DashboardLayout";
const { Title } = Typography;

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>home page</div>
		</>
	);
}
