import Head from "next/head";
import AppHeader from "../../components/AppHeader";
import { Layout, Menu, theme, Card } from "antd";
import Link from "next/link";
import { useRouter } from "next/router";
import CrawlerControls from "@/components/CrawlerControls";
import TargetPageDOMInstance from "@/components/TargetPageDOMInstance";
import ScrapperProvider, { ScrapperContext } from "@/context/ScrapperContext";
const { Content, Sider } = Layout;

export default function CrawlerCreate() {
	return (
		<>
			<Head>
				<title>Create New Crawler | Pirate Crawler</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<ScrapperProvider>
					<Content>
						<Layout>
							<Sider width={300} className="setting-controls">
								<CrawlerControls />
							</Sider>
							<Content className="pa-4 h-100vh">
								<TargetPageDOMInstance />
							</Content>
						</Layout>
					</Content>
				</ScrapperProvider>
			</Layout>
		</>
	);
}
