import Head from "next/head";
import { Button, Card, Divider, Typography } from "antd";
import React from "react";
import DashboardLayout from "../../components/DashboardLayout";
const { Title } = Typography;
import { Space, Table, Tag } from "antd";
import type { ColumnsType } from "antd/es/table";
import { EditOutlined, DeleteOutlined } from "@ant-design/icons";

interface DataType {
	key: string;
	name: string;
	target: string;
}

export default function Crawlers() {
	const columns: ColumnsType<DataType> = [
		{
			title: "Name",
			dataIndex: "name",
			key: "name",
			render: (text) => <a>{text}</a>,
		},
		{
			title: "Target",
			dataIndex: "target",
			key: "target",
		},
		{
			title: "Action",
			key: "action",
			render: () => (
				<Space size="middle">
					<Button type="primary" icon={<EditOutlined />} />
					<Button type="primary" icon={<DeleteOutlined />} danger />
				</Space>
			),
		},
	];

	const data: DataType[] = [
		{
			key: "1",
			name: "John Brown",
			target: "New York No. 1 Lake Park",
		},
		{
			key: "2",
			name: "Jim Green",
			target: "London No. 1 Lake Park",
		},
		{
			key: "3",
			name: "Joe Black",
			target: "Sidney No. 1 Lake Park",
		},
	];

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<DashboardLayout>
				<div className="container">
					<Title level={2}>Crawlers</Title>
					<Divider />
					<Table columns={columns} dataSource={data} />
				</div>
			</DashboardLayout>
		</>
	);
}
