import Head from "next/head";
import { Typography } from "antd";
import React from "react";
import DashboardLayout from "@/components/DashboardLayout";
const { Title } = Typography;

export default function Admin() {
	return (
		<>
			<Head>
				<title>Settings | CopyKat</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<DashboardLayout>
				<div className="container">
					<Title level={2}>Feature under Development</Title>
				</div>
			</DashboardLayout>
		</>
	);
}
